// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUXFCcydPdIqmljC5rtz7eWjnMGpzNd4M',
    appId: '1:599391568661:web:002765d1d941114146df1c',
    messagingSenderId: '599391568661',
    projectId: 'aspirantes-itvh',
    authDomain: 'aspirantes-itvh.firebaseapp.com',
    storageBucket: 'aspirantes-itvh.firebasestorage.app',
    measurementId: 'G-J87RHVMPD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD7PhwpZruv5wzTrybuNgxrT40__tGWas',
    appId: '1:599391568661:android:7e1259caf5f0beb646df1c',
    messagingSenderId: '599391568661',
    projectId: 'aspirantes-itvh',
    storageBucket: 'aspirantes-itvh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBKVxT8F2rnk93MoSVC7suyftmUPzXKNE',
    appId: '1:599391568661:ios:e2817c3e0cff156146df1c',
    messagingSenderId: '599391568661',
    projectId: 'aspirantes-itvh',
    storageBucket: 'aspirantes-itvh.firebasestorage.app',
    iosBundleId: 'com.programixnavejl.aspirantesItvh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBKVxT8F2rnk93MoSVC7suyftmUPzXKNE',
    appId: '1:599391568661:ios:e2817c3e0cff156146df1c',
    messagingSenderId: '599391568661',
    projectId: 'aspirantes-itvh',
    storageBucket: 'aspirantes-itvh.firebasestorage.app',
    iosBundleId: 'com.programixnavejl.aspirantesItvh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUXFCcydPdIqmljC5rtz7eWjnMGpzNd4M',
    appId: '1:599391568661:web:19a30f362e520dc046df1c',
    messagingSenderId: '599391568661',
    projectId: 'aspirantes-itvh',
    authDomain: 'aspirantes-itvh.firebaseapp.com',
    storageBucket: 'aspirantes-itvh.firebasestorage.app',
    measurementId: 'G-158R54DL7Y',
  );
}
